# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:54
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the picture name (e.g. Seating Area, or Kitchen)', max_length=100)),
                ('url', models.CharField(help_text='This is to access the picture later.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter the restaurant name (e.g. Santarpio's or Jimmy's Subs)", max_length=100)),
                ('description', models.TextField(help_text='Enter a brief description of the restaurant', max_length=1000)),
                ('address', models.CharField(help_text='123 Sample St, City ST 90210', max_length=75)),
                ('hours', models.CharField(help_text='Enter the restaurant hours (e.g. M-F 9-5, Sat 12-5, Sun Closed)', max_length=200)),
                ('category', models.TextField(help_text='Enter the general food category (e.g. Mexican, American, Thai, etc)', max_length=50)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(help_text='Select pictures for this restaurant', to='swiper.Picture')),
            ],
        ),
    ]
