# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0003_auto_20171031_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(help_text='List of matches for each user to a restaurant.', to='swiper.Restaurant'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/2017-11-04 16:02:03.831260'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<django.db.models.query_utils.DeferredAttribute object at 0x107659908>'),
        ),
    ]
