# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0004_auto_20171104_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_location_x',
            field=models.DecimalField(decimal_places=6, default=42.3601, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_location_y',
            field=models.DecimalField(decimal_places=6, default=71.0589, max_digits=9),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/2017-12-04 02:08:40.895105'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<django.db.models.query_utils.DeferredAttribute object at 0x108e53978>'),
        ),
    ]
