# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0005_auto_20171203_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/2017-12-10 22:12:19.128357'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<django.db.models.query_utils.DeferredAttribute object at 0x108750978>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
