# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0007_auto_20171212_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='match',
            name='deny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_matched',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
