# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0008_auto_20171212_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
