# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0008_auto_20171210_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<django.db.models.query_utils.DeferredAttribute object at 0x10df22978>'),
        ),
    ]
