# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swiper', '0009_auto_20171210_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_matched', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_location_x',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_location_y',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<function now at 0x103c54510>'),
        ),
        migrations.AddField(
            model_name='match',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_restaurant', to='swiper.Restaurant'),
        ),
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
