# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, default=40.7128, max_digits=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, default=-74.006, max_digits=9),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='Boston, MA', help_text='123 Sample St, City ST 90210', max_length=125),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='Boston, MA', help_text='123 Sample St, City ST 90210', max_length=125),
        ),
    ]
