# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0009_auto_20171212_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_matched',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/'),
        ),
    ]
