# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0010_auto_20171220_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='A generic restaurant.', help_text='Enter a brief description of the restaurant', max_length=1000),
        ),
    ]
