# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swiper', '0010_auto_20171212_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_denied', models.DateField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny_restaurant', to='swiper.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
