# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0010_auto_20171211_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='swiper/static/img/no-img.png', upload_to='swiper/static/img/<function now at 0x11104c510>'),
        ),
    ]
