# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0013_auto_20171220_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_group',
            field=models.BooleanField(default=False),
        ),
    ]
